### ISSUE TITLE
Channel does not work on Roku 3

### ISSUE THREAD

**Issue by seagull** [r15ch13/Hitbox.tv.bundle#1]
Hi;
Attempting to view a channel produces a video error.
I've taken a picture to show it.
https://i.imgur.com/j2ZnDY5.jpg

This has been the case since the first version; tested with 1.2.0 (Nov 2) as well.

Thanks!

**Comment by seagull** [comment]
If the developer does not have a Roku, I am more than happy to test out developmental builds.
My email is seagull at seagull dot io.

**Comment by r15ch13** [comment]
It seems so that Roku doesn't support the RTMP protocol. I can't find a solution for that at the time.

**Comment by r15ch13** [comment]
Hitbox now supports HLS. Could you try it again with the new version?

**Comment by seagull** [comment]
IT WORKS!
life is livable again.

thank you sir!
